// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_asp.net_core.Data;

#nullable disable

namespace Web_asp.net_core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240324081502_TenMigration")]
    partial class TenMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Web_asp.net_core.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaSanPham");

                    b.HasIndex("SoHoaDon");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("Web_asp.net_core.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Web_asp.net_core.Models.DaiLy", b =>
                {
                    b.Property<int>("MaDaiLy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDaiLy"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("NoDauKy")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenChuDaiLy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaDaiLy");

                    b.ToTable("DaiLies");
                });

            modelBuilder.Entity("Web_asp.net_core.Models.HoaDon", b =>
                {
                    b.Property<int>("SoHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SoHD"));

                    b.Property<int>("MaDaiLy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLapHoaDon")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SoHD");

                    b.HasIndex("MaDaiLy");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("Web_asp.net_core.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<decimal>("DonGiaTraCham")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal>("DonGiaTraGop")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal>("DonGiaTraNgay")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaSanPham");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("Web_asp.net_core.Models.ThanhToan", b =>
                {
                    b.Property<int>("SoPhieuThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SoPhieuThu"));

                    b.Property<int>("MaDaiLy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLapPhieu")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("SoPhieuThu");

                    b.HasIndex("MaDaiLy");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("Web_asp.net_core.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("Web_asp.net_core.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_asp.net_core.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("SoHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Web_asp.net_core.Models.HoaDon", b =>
                {
                    b.HasOne("Web_asp.net_core.Models.DaiLy", "DaiLy")
                        .WithMany()
                        .HasForeignKey("MaDaiLy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaiLy");
                });

            modelBuilder.Entity("Web_asp.net_core.Models.ThanhToan", b =>
                {
                    b.HasOne("Web_asp.net_core.Models.DaiLy", "DaiLy")
                        .WithMany()
                        .HasForeignKey("MaDaiLy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaiLy");
                });
#pragma warning restore 612, 618
        }
    }
}
